homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 59.65
  longitude: 9.65
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  api_password: !secret http_password
  ssl_certificate: /home/homeassistant/dehydrated/certs/aikio.duckdns.org/fullchain.pem
  ssl_key: /home/homeassistant/dehydrated/certs/aikio.duckdns.org/privkey.pem
  base_url: aikio.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
#map:

# Track the sun
sun:

# Text to speech
#tts:
#  - platform: google

# Cloud
#cloud:

#panel_iframe: 
#  configurator:
#    title: "Configurator"
#    icon: mdi:wrench
#    url: https://hassbian.local:3218/    

rfxtrx:
    device: /dev/ttyUSB0

mqtt:
  broker: 192.168.0.82
  username: Admin
  password: !secret http_password
  
wake_on_lan: # enables `wake_on_lan` domain

notify:
  - platform: webostv
    host: 192.168.0.95
    name: LG_TV
    filename: webostv.conf
  - platform: pushbullet
    name: pushbullet
    api_key: o.nQm956gV097XBLdRdrrAlr8injaGhKLM
    

media_player:
  - platform: webostv
    name: LG TV  
    host: 192.168.0.95
    #other settings
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: C8-08-E9-DB-34-B0
    customize:
      sources:
        - youtube
        - netflix
        - hdmi2
  - platform: denonavr
    name: Receiver
    host: 192.168.0.91
  - platform: spotify
    client_id: 4f2c6f72c61e4204baeb3700c5fdec98
    client_secret: bcbd331316874e02b0d8ae4f4eff490f

sensor: !include sensors.yaml
switch: !include switch.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

input_number:
  alarm_clock_hour:
    initial: 6
    min: 0
    max: 23
    step: 1
  alarm_clock_minute:
    initial: 30
    min: 0
    max: 55
    step: 5

input_boolean:
  alarm_clock_status:
    initial: off
